export enum MoveCallStatus {
    ENTER_PACKAGE_ID,
    CHOOSE_MODULE,
    CHOOSE_FUNCTION,
    ENTER_ARGS,
    CALL,
    FINISH,
    ERROR,
};

export enum MoveCallActionType {
    SET_MNEMONICS = "SET_MNEMONICS",
    SET_PACKAGE_ID = "SET_PACKAGE_ID",
    SET_MODULES = "SET_MODULES",
    SET_ERROR = "SET_ERROR",
    SET_CURRENT_MODULE = "SET_CURRENT_MODULE",
    SET_FUNCTIONS = "SET_FUNCTIONS",
    SET_CURRENT_FUNCTION = "SET_CURRENT_FUNCTION",
};